default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: rails_user
  password: rails_user
  timeout: 5000
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: rails-local_development

test:
  <<: *default
  database: rails-local_test

production:
  <<: *default
  database: rails-local_production
