# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7535a558d6e4bbd5b50d0b94ca9847c3da96609c2188ed02753e39b84c22f86acf28ba4aa2ea25b99f06e4558054b8374728eb7898bd37839405a4e5ecffd8c1

test:
  secret_key_base: d8240b2a91c8ad7c9d722804b126a91d26d3c3d41b641beb331a771a4df8b937448b86474624da357ee61bfb8b7fa97355cef8c6172361f8a4eb92f002a3013c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
